//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.14 at 03:32:24 PM MST 
//


package org.hl7.fhirpath.tests;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.hl7.fhirpath.tests package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Tests_QNAME = new QName("http://hl7.org/fhirpath/tests", "tests");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.hl7.fhirpath.tests
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Tests }
     * 
     */
    public Tests createTests() {
        return new Tests();
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link Test }
     * 
     */
    public Test createTest() {
        return new Test();
    }

    /**
     * Create an instance of {@link Expression }
     * 
     */
    public Expression createExpression() {
        return new Expression();
    }

    /**
     * Create an instance of {@link Output }
     * 
     */
    public Output createOutput() {
        return new Output();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Tests }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hl7.org/fhirpath/tests", name = "tests")
    public JAXBElement<Tests> createTests(Tests value) {
        return new JAXBElement<Tests>(_Tests_QNAME, Tests.class, null, value);
    }

}
